version: '3'

services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
  
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
      
    ports:
      - "8080:80"
    depends_on:
      - rabbitmq